// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqt9q8zI6vIXpwDnvQD1a0DXhjRblmLD4',
    appId: '1:337431803216:web:ab9e1d8b856de238bda855',
    messagingSenderId: '337431803216',
    projectId: 'authentication-app-894fa',
    authDomain: 'authentication-app-894fa.firebaseapp.com',
    storageBucket: 'authentication-app-894fa.appspot.com',
    measurementId: 'G-JRK1EYQM0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm7C8ZU4_zRVG8LMKfS6TQV27fx-RMdlQ',
    appId: '1:337431803216:android:15eb6b0a62314a10bda855',
    messagingSenderId: '337431803216',
    projectId: 'authentication-app-894fa',
    storageBucket: 'authentication-app-894fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMOXyZftBRS8yMGfz5ZpUztJYSl5tdIZs',
    appId: '1:337431803216:ios:eb2a01058c269e6ebda855',
    messagingSenderId: '337431803216',
    projectId: 'authentication-app-894fa',
    storageBucket: 'authentication-app-894fa.appspot.com',
    iosBundleId: 'com.example.authenticationApp',
  );
}
